version: 2.1

commands:
  initial-machine-setup:
    description: "Initial Machine Setup"
    steps:
      - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - initial-machine-setup
      - checkout
      - run:
          name: Setup Project
          command: npm run setup
      - save_cache:
          key: "npm-packages"
          paths:
            - node_modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - initial-machine-setup
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: Setup Project
          command: npm run setup
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - initial-machine-setup
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: Setup Project
          command: npm run setup
      - run: npm audit


workflows:
  backend:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
