version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Setup Project
          command: npm run setup
      - save_cache:
          key: "npm-packages"
          paths:
            - node_modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: Setup Project
          command: npm run setup
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: Setup Project
          command: npm run setup
      - run: npm audit


workflows:
  backend:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
